### ISSUE TITLE
double input in inference.py to model, giving error. Can you please explain ?

### ISSUE THREAD

**Issue by gouravchat** [pasquini-dario/InterpretablePPSM#2]
double input in inference.py to model, giving error. Can you please explain ?

**Comment by pasquini-dario** [comment]
Hi,

could you give me more information on the error?

**Comment by gouravchat** [comment]
When I train the model with my password dataset,  it does a periodic evaluation . So then it is doing self.model(H,I) but the model has only one input.. so it is throwing error ..   but actual model has only one input so training is not giving any problem?  M I doing anything wrong

**Comment by gouravchat** [comment]
Please check the inference.py file

**Comment by gouravchat** [comment]
input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)
  File "/anaconda/envs/azureml_py38_tensorflow/lib/python3.8/site-packages/keras/engine/input_spec.py", line 199, in assert_input_compatibility
    raise ValueError('Layer ' + layer_name + ' expects ' +
ValueError: Layer model expects 1 input(s), but it received 2 input tensors. Inputs received: [<tf.Tensor: shape=(1548, 16), dtype=int64, numpy=
array([[ 3, 31, 18, ...,  0,  0,  0],
       [40,  3, 18, ...,  0,  0,  0],
       [40, 31,  3, ...,  0,  0,  0],
       ...,
       [47, 67, 21, ...,  0,  0,  0],
       [47, 67, 21, ...,  0,  0,  0],
       [47, 67, 21, ...,  0,  0,  0]])>, <tf.Tensor: shape=(1548, 16), dtype=int64, numpy=
array([[ 0,  1,  2, ..., 13, 14, 15],
       [ 0,  1,  2, ..., 13, 14, 15],
       [ 0,  1,  2, ..., 13, 14, 15],
       ...,
       [ 0,  1,  2, ..., 13, 14, 15],
       [ 0,  1,  2, ..., 13, 14, 15],
       [ 0,  1,  2, ..., 13, 14, 15]])>]

**Comment by pasquini-dario** [comment]
It should work now. Apparently, I erroneously uploaded an old version of inference.py. I've just updated it.
Please, let me know if you have other problems.

**Comment by gouravchat** [comment]
> It should work now. Apparently, I erroneously uploaded an old version of inference.py. I've just updated it. Please, let me know if you have other problems.

ket me check

**Comment by gouravchat** [comment]
> > It should work now. Apparently, I erroneously uploaded an old version of inference.py. I've just updated it. Please, let me know if you have other problems.
> 
> ket me check

ti works  thanks
