### ISSUE TITLE
Tensorflow error

### ISSUE THREAD

**Issue by gouravchat** [pasquini-dario/InterpretablePPSM#3]
As the author is suggesting tensorflow<2.0, what version of tensorflow_addons it will support? Can you please provide the requirements,txt file ?

**Comment by pasquini-dario** [comment]
As I wrote in the readme file, to run the jupyter notebook (i.e., Meter_interface_poc.ipynb) you need tensorflow<2.0. 
However, to run the other scripts (e.g., train.py and apply.py), tensorflow>2.0 is required.

If you are looking for the version of tensorflow_addons, I imagine that you want to use train.py and apply.py.
In this case, tensorflow 2.5 and  tensorflow_addons 0.10 should work.

**Comment by gouravchat** [comment]
> As I wrote in the readme file, to run the jupyter notebook (i.e., Meter_interface_poc.ipynb) you need tensorflow<2.0. However, to run the other scripts (e.g., train.py and apply.py), tensorflow>2.0 is required.
> 
> If you are looking for the version of tensorflow_addons, I imagine that you want to use train.py and apply.py. In this case, tensorflow 2.5 and tensorflow_addons 0.10 should work.

Thanks for the help
